### ISSUE TITLE
v2.0 error building on Mac OS

### ISSUE THREAD

**Issue by iwasrobbed** [audiojs/audio-speaker#47]
cc @connorhartley 

Here are the logs from running `yarn add audiojs/audio-speaker#release-2.0-browser`

#### Config
- Mac OS X Sierra (10.12.5)
- node -v: v6.9.1
- electron-prebuilt-compile: 1.6.11

### Verbose output
https://gist.github.com/iwasrobbed/6a27a0e7e9cb74f1874a67c7e9ab101e

### Compact output

> yarn add v0.17.10
> warning blah@0.0.0: License should be a valid SPDX license expression
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> warning 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
> info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
> warning 7zip-bin-win@2.1.0: The platform "darwin" is incompatible with this module.
> info "7zip-bin-win@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] 🔗  Linking dependencies...
> [4/4] 📃  Building fresh packages...
> [1/1] ⠁ audio-mpg123: Failed to execute '/Users/rob/.nvm/versions/node/v6.9.1/bin/node /Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modul
> [-/1] ⠁ waiting...
> [-/1] ⠁ waiting...
> [-/1] ⠁ waiting...
> error Error running install script for optional dependency: "/Users/rob/blah/node_modules/audio-mpg123: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node ./scripts/check-pre-gyp && node-pre-gyp install --fallback-to-build\nDirectory: /Users/rob/blah/node_modules/audio-mpg123\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.36\nnode-pre-gyp info using node@6.9.1 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/rob/blah/node_modules/audio-mpg123/lib/audio_mpg123.node\" (not found)\nnode-pre-gyp http GET https://github.com/audiojs/audio-mpg123/releases/download/1.2.3/audio_mpg123-v1.2.3-node-v48-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://github.com/audiojs/audio-mpg123/releases/download/1.2.3/audio_mpg123-v1.2.3-node-v48-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://github.com/audiojs/audio-mpg123/releases/download/1.2.3/audio_mpg123-v1.2.3-node-v48-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for audio-mpg123@1.2.3 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://github.com/audiojs/audio-mpg123/releases/download/1.2.3/audio_mpg123-v1.2.3-node-v48-darwin-x64.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.9.1 | darwin | x64\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.9.1 | darwin | x64\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp info spawn /usr/bin/python\ngyp info spawn args [ '/Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/rob/blah/node_modules/audio-mpg123/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/rob/.node-gyp/6.9.1/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/Users/rob/.node-gyp/6.9.1',\ngyp info spawn args   '-Dnode_gyp_dir=/Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/Users/rob/blah/node_modules/audio-mpg123',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\n2017-08-01 23:11:39.296 xcodebuild[83636:2605686] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XCSwiftr.xcplugin' not present in DVTPlugInCompatibilityUUIDs\n2017-08-01 23:11:39.297 xcodebuild[83636:2605686] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs\n2017-08-01 23:11:39.298 xcodebuild[83636:2605686] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/UncrustifyPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs\n2017-08-01 23:11:39.299 xcodebuild[83636:2605686] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Swimat.xcplugin' not present in DVTPlugInCompatibilityUUIDs\n2017-08-01 23:11:39.300 xcodebuild[83636:2605686] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.9.1 | darwin | x64\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp info spawn make\ngyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]\n  CC(target) Release/obj.target/module/src/mpg123/src/libout123/modules/coreaudio.o\nIn file included from ../src/mpg123/src/libout123/modules/coreaudio.c:12:\nIn file included from ../src/mpg123/src/libout123/out123_int.h:17:\n../src/mpg123/src/libout123/module.h:13:10: fatal error: 'ltdl.h' file not found\n#include <ltdl.h>\n         ^\n1 error generated.\nmake: *** [Release/obj.target/module/src/mpg123/src/libout123/modules/coreaudio.o] Error 1\ngyp ERR! build error \ngyp ERR! stack Error: `make` failed with exit code: 2\ngyp ERR! stack     at ChildProcess.onExit (/Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)\ngyp ERR! System Darwin 16.6.0\ngyp ERR! command \"/Users/rob/.nvm/versions/node/v6.9.1/bin/node\" \"/Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/rob/blah/node_modules/audio-mpg123/lib/audio_mpg123.node\" \"--module_name=audio_mpg123\" \"--module_path=/Users/rob/blah/node_modules/audio-mpg123/lib\"\ngyp ERR! cwd /Users/rob/blah/node_modules/audio-mpg123\ngyp ERR! node -v v6.9.1\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute '/Users/rob/.nvm/versions/node/v6.9.1/bin/node /Users/rob/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rob/blah/node_modules/audio-mpg123/lib/audio_mpg123.node --module_name=audio_mpg123 --module_path=/Users/rob/blah/node_modules/audio-mpg123/lib' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rob/blah/node_modules/node-pre-gyp/lib/util/compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:106:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)\nnode-pre-gyp ERR! System Darwin 16.6.0\nnode-pre-gyp ERR! command \"/Users/rob/.nvm/versions/node/v6.9.1/bin/node\" \"/Users/rob/blah/node_modules/audio-mpg123/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /Users/rob/blah/node_modules/audio-mpg123\nnode-pre-gyp ERR! node -v success Saved lockfile.
> success Saved 26 new dependencies.
> ├─ atob-lite@2.0.0
> ├─ audio-buffer-from@1.0.3
> ├─ audio-buffer-list@3.2.1
> ├─ audio-buffer-utils@5.1.1
> ├─ audio-buffer@4.0.2
> ├─ audio-context@1.0.1
> ├─ audio-format@2.2.1
> ├─ audio-mpg123@1.2.3
> ├─ audio-speaker@2.0.0-5
> ├─ clamp@1.0.1
> ├─ dom-walk@0.1.1
> ├─ global@4.3.2
> ├─ is-audio-buffer@1.0.11
> ├─ is-base64@0.0.4
> ├─ is-browser@2.0.1
> ├─ is-negative-zero@2.0.0
> ├─ is-plain-obj@1.1.0
> ├─ min-document@2.19.0
> ├─ nan@2.2.1
> ├─ negative-index@1.0.2
> ├─ node-pre-gyp@0.6.36
> ├─ pcm-convert@1.6.3
> ├─ process@0.5.2
> ├─ sample-rate@2.0.0
> ├─ string-to-arraybuffer@1.0.0
> └─ web-audio-write@1.2.1
> warning blah@0.0.0: License should be a valid SPDX license expression
> $ install-app-deps
> ⚠️  Please use as subcommand: electron-builder install-app-deps
> electron-builder 19.18.0
> Rebuilding native production dependencies for darwin:x64
> Rebuilding native dependency audio-mpg123
> ⚠️  Cannot build optional native dep audio-mpg123
> ✨  Done in 20.37s.

**Comment by connorhartley** [comment]
I've found someone who will be able to manage the pre-built builds for mac for a little while, but long term for that I might need to find someone more permanent. 

The issue you're having is that your device does not have the build tools (xcode and some others) to build the native binding itself, in which it goes to find a pre-built binding for your system (but can't because of the first paragraph). https://github.com/nodejs/node-gyp#on-mac-os-x has the requirements you would need.

Otherwise I will try get a pre-built binding up for mac this week and I will let you know when you can try it again. Release 2.0 needs as much testing as it can get so we can really make it an improvement on top of the existing system, so thank you for trying it out.

**Comment by iwasrobbed** [comment]
@connorhartley Unfortunately, I already have Xcode and the CLI tools installed (as I'm an iOS dev). If I can try anything else, let me know and I'd be happy to. I've also installed `node-gyp` globally.

I'm not in any rush, so I'll happily test out what you all have on my daily-use personal project.

Thanks again for the help
