### ISSUE TITLE
Cannot set property writableObjectMode of #<Duplex> which has only a getter

### ISSUE THREAD

**Issue by SinanAkkoyun** [audiojs/audio-speaker#63]
TypeError: Cannot set property writableObjectMode of #<Duplex> which has only a getter
    at Object.<anonymous> (./node_modules/audio-through/index.js:162:38)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Object.S (./node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (./node_modules/audio-speaker/stream.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Object.S (./node_modules/tsx/dist/cjs/index.cjs:1:1292)

Node.js v21.7.1

**Comment by y-lobau** [comment]
Same issue for me on mac. Doing just this:

```
import createSpeaker from 'audio-speaker';
let output = createSpeaker();
```

**Comment by acornejo** [comment]
Ditto.

I suspect, also using node V21.

I suspect something change in the most recent releases of nodejs that prevents this library from working :(

**Comment by acornejo** [comment]
Ohh, its easier than that writable.writableObjectMode is a read only property, and has been that way for a long time, so I guess it just means nodejs added stricter checking.

**Comment by dy** [comment]
Fixed in v2 — audio-through removed entirely. Stream API now uses standard Node Writable, no prototype hacks.
